### ISSUE TITLE
akcess is not picking default kubeconfig

### ISSUE THREAD

**Issue by isindir** [viveksinghggits/akcess#9]
akcess is not picking default kube config, confgiured as exported variable `KUBECONFIG`:

```
% akcess allow --verb get --resource pods,pods/log -n jenkins
Error: namespace jenkins was not found: Get "https://api.crc.testing:6443/api/v1/namespaces/jenkins": dial tcp: lookup api.crc.testing on 8.8.8.8:53: no such host
```

Only if flag `-k` is passed it works.

**Comment by viveksinghggits** [comment]
Hi @isindir,
can you please make sure if `HOME` env var is set on your  machine. If that env var is set it should work. HOME or respective env var in windows (I am assuming you are on windows).
Basically, whatever this utility returns
https://pkg.go.dev/os#UserHomeDir

**Comment by isindir** [comment]
@viveksinghggits I'm using `macos` (where `HOME` is set) and as for location of kubernetes configuration I have tried 2 options:
* my default setup - I'm using `kubie` and `kubectl`/`helm` and other tools are working fine with that
* I copied configuration file to `~/some-config` and exported it in the shell as `export KUBECONFIG=~/some-config`

in both cases it was not fully operational, also in 2nd case I was able to use with `-k` flag, like: `akccess allow -k ~/some-config ...`

**Comment by viveksinghggits** [comment]
If `HOME` is set correctly, things should work. Can you please confirm that `HOME` is set and your kubeconfig file is located at `$HOME/.kube/config`.

**Comment by isindir** [comment]
I can confirm that my `HOME` is set correctly, but as kubernetes user, I don't expect to have config file only in it's default location - I think application should treat kube client configuration same way as `kubectl` and allow me to specify config file using environment variable as well.

In many cases I'm using multiple clusters and these clusters are configured in multiple files and locations, kube ecosystem allows it.

**Comment by viveksinghggits** [comment]
> allow me to specify config file using environment variable as well.

@isindir this a know issue, `akcess` doesn't honor `KUBECONFIG` env var as of now.

> application should treat kube client configuration same way as kubectl

kubectl also looks for the config file at `$HOME/.kube/config`. and thats where akcess is also looking for the kube config file.

So here is how the flow is, 
1. Create a config from the kubeconfig if it has been provided as `-k` flag.
2. fall back to the default location of kubeconfig file that is `$HOME/.kube/config` (this is default location even in case of kubectl)

What I can do, is to make sure that akcess is also honoring the `KUBECONFIG` env var, would that work for you? Because if kubectl is working with the default kubeconfig file, akcess would also work for sure.

**Comment by isindir** [comment]
@viveksinghggits  This will work, but it also needs to take into account default context if that is set

**Comment by viveksinghggits** [comment]
@isindir  It take care of that even now.

**Comment by viveksinghggits** [comment]
@isindir should we close this in favour of #11? I will be pushing the fix in sometime.
